name: 'node-yarn-cache'
description: 'Checkout Code, Setup Node and YARN Cache by SO'

inputs:
  token:
    required: true
    description: 'token'
  fetch-depth:
    required: false
    description: 'fetch-depth'
    default: 1
  ref:
    required: false
    description: 'ref'
    default: ''
  node-version:
    required: false
    description: 'node version'
    default: '18.x'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}

    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

branding:
  icon: 'aperture'
  color: 'blue'
